var DiQuestions = {
  preferences: [
    // DiQuestions about favorites and traits
    "What is your favorite color?",
    "Do you prefer reading books or watching movies?",
    "Are you a morning person or a night owl?",
    "What is your favorite type of cuisine?",
    "Do you enjoy outdoor activities?",
    "What is your favorite animal?",
    "Are you a coffee or tea person?",
    "What is your preferred mode of transportation?",
    "Do you enjoy listening to podcasts?",
    "Are you a cat or a dog person?",
    "What is your favorite season of the year?",
    "Do you enjoy cooking?",
    "Are you interested in art or music?",
    "What is your favorite movie genre?",
    "Do you enjoy playing sports?",
    "Are you a city person or a nature lover?",
    "What is your favorite type of exercise?",
    "Do you enjoy solving puzzles or brain teasers?",
    "Are you a fan of technology?",
    "What is your favorite type of dessert?",
    "Do you enjoy traveling?",
    "Are you more introverted or extroverted?",
    "What is your favorite type of music?",
    "Do you enjoy going to concerts?",
    "What is your favorite book or genre?",
    "Are you a fan of video games?",
    "Do you prefer sweet or savory foods?",
    "What is your preferred method of communication?",
    "Are you a sports fan?",
    "What is your favorite hobby?",
    "Do you enjoy dancing?",
    "Are you a beach person or a mountain person?",
    "What is your favorite type of TV show?",
    "Do you like attending live events?",
    "What is your favorite type of weather?",
    "Are you a fan of social media?",
    "What is your favorite type of drink?",
    "Do you enjoy gardening?",
    "Are you interested in politics?",
    "What is your favorite type of art?",
    "Do you enjoy learning new languages?",
    "Are you a fan of superheroes?",
    "What is your favorite type of comedy?",
    "Do you enjoy hiking?",
    "Are you a fan of board games?",
    "What is your favorite type of car?",
    "Do you enjoy photography?",
    "Are you a fan of musicals?",
    "What is your favorite type of dance?",
    "Do you enjoy shopping?",
    "Are you interested in history?",
  ],
  expectations: [

    // Questions about what the person is looking for in a community
    "What values or principles are important to you in a community?",
    "What type of activities or events would you like to see in a community?",
    "Are you interested in participating in volunteer work within the community?",
    "Do you prefer a close-knit community or a larger, more diverse community?",
    "What level of involvement do you want to have in the community?",
    "Are you looking for a community that focuses on a specific interest or hobby?",
    "How important is it for you to have access to community facilities or amenities?",
    "Do you prefer a community with a structured leadership or a more self-organized community?",
    "What kind of communication channels would you like to have with other community members?",
    "Are you interested in networking and making professional connections within the community?",
    "Do you prefer a community that is more focused on personal growth and self-improvement or socializing and having fun?",
    "Are you looking for a community that offers educational opportunities or workshops?",
    "Do you value a community that promotes diversity and inclusivity?",
    "Are you interested in a community that organizes group trips or outings?",
    "Do you prefer a community that has a strong online presence or one that primarily interacts offline?",
    "How important is it for you to have access to resources and support from community members?",
    "Are you looking for a community that has regular meetings or gatherings?",
    "Do you prefer a community that is more laid-back and casual or one that is more structured and organized?",
    "Are you interested in a community that promotes health and wellness activities?",
    "What is your preferred method of communication within the community (e.g., online forums, social media, email, in-person)?",
    "Do you value a community that promotes environmental sustainability?",
    "Are you interested in a community that offers mentorship or coaching programs?",
    "Do you prefer a community that is geographically local or one that is more dispersed?",
    "How important is it for you to have a sense of belonging and connection within the community?",
    "Are you looking for a community that organizes cultural or artistic events?",
    "Do you value a community that encourages collaboration and teamwork?",
    "Are you interested in a community that provides business or entrepreneurial support?",
    "Do you prefer a community with a strong sense of shared identity or one that celebrates diversity?",
    "How important is it for you to have access to social activities and gatherings?",
    "Are you looking for a community that offers resources for personal development and growth?",
    "Do you value a community that supports local businesses and initiatives?",
    "Are you interested in a community that advocates for social or political causes?",
    "What is your preferred level of interaction and engagement with other community members?",
    "Do you prefer a community that is more family-oriented or one that caters to individuals or couples?",
    "How important is it for you to have opportunities for collaboration and co-creation within the community?",
    "Are you looking for a community that provides mentorship opportunities for newcomers?",
    "Do you value a community that organizes outdoor or nature-related activities?",
    "Are you interested in a community that promotes lifelong learning and education?",
    "What level of commitment are you willing to invest in a community?",
    "Do you prefer a community with formal membership or one that is open and inclusive?",
    "How important is it for you to have access to recreational facilities or programs?",
    "Are you looking for a community that encourages personal exploration and self-discovery?",
    "Do you value a community that promotes intergenerational connections?",
    "Are you interested in a community that supports local charities or social causes?",
    "What is your preferred mode of participation within the community (e.g., attending events, contributing ideas, leading projects)?",
    "Do you prefer a community that is more tech-savvy and utilizes digital tools and platforms?",
    "How important is it for you to have access to cultural or artistic experiences within the community?",
    "Are you looking for a community that encourages sustainability practices and initiatives?",

  ],
  needs: [

    // Questions about what the person might need from the community
    "What support or assistance do you expect from the community?",
    "What skills, resources, or expertise can you offer to the community?",
    "Are you willing to actively contribute to the community's activities and initiatives?",
    "Do you need mentorship or guidance in any specific area?",
    "Are you looking for opportunities to collaborate on projects or initiatives?",
    "Do you require emotional support or a sense of belonging from the community?",
    "Are you in need of professional networking opportunities within the community?",
    "Do you need access to specific resources or information from the community?",
    "Are you interested in participating in community-led educational programs or workshops?",
    "Do you require help or advice related to a specific hobby or interest?",
    "Are you looking for opportunities to give back to the community through volunteering?",
    "Do you need assistance in finding job opportunities or career guidance?",
    "Are you interested in receiving mentorship or guidance from experienced community members?",
    "Do you require financial support or access to funding opportunities from the community?",
    "Are you in need of housing or accommodation assistance from the community?",
    "Do you need help or recommendations for local services or businesses?",
    "Are you interested in forming professional or personal collaborations with community members?",
    "Do you require health or wellness support from the community?",
    "Are you in need of language or cultural integration assistance from the community?",
    "Do you need help or advice related to personal or professional development?",
    "Are you interested in finding potential clients or customers within the community?",
    "Do you require assistance with childcare or family-related services?",
    "Are you looking for recommendations or advice related to local events or activities?",
    "Do you need assistance or guidance in navigating community resources or services?",
    "Are you interested in connecting with people who share a similar background or experience?",
    "Do you require support or assistance in organizing community events or initiatives?",
    "Are you in need of transportation assistance from the community?",
    "Do you need recommendations or advice for local healthcare or medical services?",
    "Are you interested in finding a mentor or role model within the community?",
    "Do you require assistance or recommendations for educational opportunities?",
    "Are you looking for opportunities to showcase your talents or skills within the community?",
    "Do you need support or advice related to starting a business or entrepreneurship?",
    "Are you interested in receiving feedback or critique for your creative work?",
    "Do you require legal or financial advice from the community?",
    "Are you in need of support or resources for mental health or well-being?",
    "Do you need assistance or recommendations for local government services?",
    "Are you interested in forming social connections and friendships within the community?",
    "Do you require help or advice related to navigating the local housing market?",
    "Are you looking for opportunities to collaborate on social or environmental initiatives?",
    "Do you need support or advice related to parenting or family matters?",
    "Are you interested in finding potential business partners or collaborators within the community?",
    "Do you require assistance or recommendations for local transportation options?",
    "Are you in need of legal or immigration-related support from the community?",
    "Do you need help or advice related to financial planning or budgeting?",
    "Are you interested in finding potential job opportunities within the community?",
    "Do you require assistance or recommendations for local educational institutions?",
    "Are you looking for opportunities to contribute to community projects or initiatives?",
    "Do you need support or advice related to navigating the local healthcare system?",
    "Are you interested in finding mentors or advisors for a specific field or industry?",
    "Do you require assistance or recommendations for local cultural or recreational activities?",
    "Are you in need of support or resources for substance abuse or addiction?",
    "Do you need help or advice related to navigating the local legal system?",
    "Are you interested in finding potential investors or funding opportunities within the community?",
    "Do you require assistance or recommendations for local community services?",
    "Are you looking for opportunities to contribute to environmental sustainability efforts within the community?",
    "Do you need support or resources for caregiving or eldercare?",
    "Are you interested in finding potential collaborators or team members for a specific project?",
    "Do you require assistance or recommendations for local food or grocery options?",
    "Are you in need of support or resources for physical disabilities or accessibility?",
    "Do you need help or advice related to navigating the local education system?",
    "Are you interested in finding potential clients or customers for your business within the community?",
    "Do you require assistance or recommendations for local social services?",
    "Are you looking for opportunities to contribute to community advocacy or social justice?",
    "Do you need support or resources for LGBTQ+ issues or concerns?",
    "Are you interested in finding potential study or research partners within the community?",
    "Do you require assistance or recommendations for local cultural or artistic institutions?",
    "Are you in need of support or resources for mental health or counseling?",
    "Do you need help or advice related to navigating the local transportation system?",
    "Are you interested in finding potential volunteers or helpers for a specific project?",
    "Do you require assistance or recommendations for local recreational or sports activities?",
    "Are you looking for opportunities to contribute to community development or urban planning?",
    "Do you need support or resources for specific health conditions or illnesses?",
    "Are you interested in finding potential language exchange partners within the community?",
    "Do you require assistance or recommendations for local employment agencies or services?",
    "Are you in need of support or resources for gender-related concerns or issues?",
    "Do you need help or advice related to navigating the local housing rental market?",
    "Are you interested in finding potential collaborators or team members for a creative project?",
    "Do you require assistance or recommendations for local technology or IT services?",
    "Are you looking for opportunities to contribute to community mentorship programs?",
    "Do you need support or resources for specific cultural or religious practices?",
    "Are you interested in finding potential travel or adventure companions within the community?",
    "Do you require assistance or recommendations for local disability services or support?",
    "Are you in need of support or resources for parenting or child-rearing?",
    "Do you need help or advice related to navigating the local business landscape?",
    "Are you interested in finding potential language teachers or tutors within the community?",
    "Do you require assistance or recommendations for local arts and entertainment options?",
    "Are you looking for opportunities to contribute to community fundraising or charity events?",
    "Do you need support or resources for specific dietary or nutritional concerns?",
    "Are you interested in finding potential research or academic collaborators within the community?",
    "Do you require assistance or recommendations for local pet services or animal care?",
    "Are you in need of support or resources for specific addictions or dependencies?",
    "Do you need help or advice related to navigating the local cultural norms and etiquette?",
    "Are you interested in finding potential team members or co-founders for a startup?",
    "Do you require assistance or recommendations for local legal or immigration services?",
    "Are you in need of support or resources for grief or bereavement?",
    "Do you need support or advice related to navigating the local educational system?",
    "Are you interested in finding potential volunteers or helpers for community initiatives?",
    "Do you require assistance or recommendations for local fitness or wellness services?",
    "Are you in need of support or resources for specific mental health conditions?",
    "Do you need help or advice related to navigating the local social and cultural scene?",
    "Are you interested in finding potential study or research opportunities within the community?",
    "Do you require assistance or recommendations for local environmental organizations or initiatives?",
    "Are you in need of support or resources for specific medical conditions?",
    "Do you need support or advice related to navigating the local job market?",
    "Are you interested in finding potential mentors or role models within the community?",
    "Do you require assistance or recommendations for local parenting or family support groups?",
    "Are you in need of support or resources for specific cultural integration or adaptation?",
    "Do you need help or advice related to navigating the local government or bureaucracy?",
    "Are you interested in finding potential investors or financial advisors within the community?"

  ]
};

const DiEvents =
{
  ND: {
    "Movie night": "Sensory-friendly movie night with adjusted lighting and sound levels.",
    "Art therapy": "Art therapy workshop focusing on self-expression and creativity.",
    "Social skills": "Social skills and communication workshop with interactive activities.",
    "Nature walk": "Nature walk and mindfulness session in a calm and peaceful environment.",
    "Music concert": "Sensory-friendly music concert featuring live performances and soothing melodies.",
    "Lego building": "Lego building competition to encourage creativity and problem-solving skills.",
    "Gaming tournament": "Gaming tournament with accessible and inclusive game options.",
    "Drama workshop": "Drama and improvisation workshop to explore emotions and build confidence.",
    "Yoga session": "Yoga and meditation session tailored for sensory needs and relaxation.",
    "Science exhibition": "Science and technology exhibition showcasing hands-on experiments and innovations.",
    "Adaptive sports": "Adaptive sports event with modified rules and equipment for inclusivity.",
    "Comic book convention": "Comic book and graphic novel convention with diverse representation and characters.",
    "Horseback riding": "Therapeutic horseback riding session to promote physical and emotional well-being.",
    "Poetry slam": "Poetry slam and spoken word performance for self-expression and storytelling.",
    "Cooking class": "Sensory-friendly cooking class focusing on taste, texture, and culinary skills.",
    "Assistive technology showcase": "Assistive technology showcase featuring innovative tools for neurodivergent individuals.",
    "Storytelling workshop": "Storytelling workshop using visual aids, puppets, or multimedia elements.",
    "Theater performance": "Sensory-friendly theater performance with relaxed rules and sensory support.",
    "Virtual reality experience": "Virtual reality experience to explore different environments and stimulate the senses.",
    "Photography excursion": "Photography excursion to capture the beauty of nature or urban landscapes.",
    "Mindfulness workshop": "Mindfulness and breathing techniques workshop for stress reduction and self-awareness.",
    "Dance class": "Accessible dance class emphasizing movement, expression, and body awareness.",
    "Neurodiversity conference": "Neurodiversity conference with speakers and panel discussions on relevant topics.",
    "Museum visit": "Sensory-friendly museum visit with guided tours and interactive exhibits.",
    "Community gardening": "Community gardening project to connect with nature and cultivate plants together.",
    "Drum circle": "Drum circle and rhythmic music therapy session for relaxation and sensory integration.",
    "Pet therapy session": "Sensory-friendly pet therapy session to interact with animals in a calm environment.",
    "LEGO Mindstorms workshop": "LEGO Mindstorms robotics workshop to explore engineering and programming concepts.",
    "Assistive communication technology": "Assistive communication technology demonstration for enhanced communication abilities.",
    "Aquarium visit": "Sensory-friendly aquarium visit with quiet hours and specialized exhibits.",
    "Relaxation workshop": "Relaxation and self-care workshop focusing on mindfulness and sensory regulation techniques.",
    "Adaptive art class": "Adaptive art class with diverse mediums and techniques to explore artistic expression.",
    "Gaming and coding workshop": "Gaming and coding workshop to foster creativity, problem-solving, and technological skills.",
    "Therapeutic gardening program": "Therapeutic gardening program to nurture plants and engage in horticultural activities.",
    "Assistive technology hackathon": "Assistive technology hackathon to develop innovative solutions for neurodivergent needs.",
    "Social meetup group": "Social meetup group for neurodivergent individuals to connect and share experiences.",
    "Drumming circle": "Drumming circle for rhythmic expression, coordination, and sensory stimulation.",
    "Outdoor adventure day": "Outdoor adventure day with hiking, canoeing, or zip-lining in an inclusive setting.",
    "Science experiment session": "Sensory-friendly science experiment session with interactive demonstrations.",
    "Inclusive dance performance": "Inclusive dance performance featuring diverse choreography and expressive movements.",
    "Board game night": "Board game night with a wide selection of games suitable for different cognitive styles.",
    "Creative writing workshop": "Creative writing workshop for self-expression and storytelling exploration.",
    "Farm visit": "Sensory-friendly farm visit with animal interactions and farm-to-table experiences.",
    "Water park day": "Sensory-friendly water park day with reduced crowds and sensory-friendly water activities.",
    "LEGO Serious Play workshop": "LEGO Serious Play workshop to facilitate team building and problem-solving.",
    "Martial arts class": "Adaptive martial arts class emphasizing discipline, self-defense, and self-confidence."
  },
  NT: {
    "Movie night": "Enjoy a movie night with friends or family.",
    "Outdoor picnic": "Have a picnic in a local park or outdoor space.",
    "Sports game": "Attend a live sports game and cheer for your favorite team.",
    "Cooking class": "Learn new culinary skills in a cooking class.",
    "Concert": "Attend a live music concert or performance.",
    "Hiking trip": "Embark on a hiking adventure and explore nature.",
    "Art exhibition": "Visit an art exhibition and appreciate various artworks.",
    "Book club": "Join a book club to discuss literature with fellow readers.",
    "Fitness class": "Take part in a fitness class, such as yoga or spinning.",
    "Volunteer work": "Engage in community service through volunteer work.",
    "Board game night": "Host a board game night with friends or family.",
    "Museum visit": "Explore museums and learn about history and culture.",
    "Beach day": "Spend a day at the beach, swimming and relaxing in the sun.",
    "Dance class": "Learn different dance styles in a dance class.",
    "Theater performance": "Attend a theater performance or play.",
    "Road trip": "Embark on a road trip to explore new destinations.",
    "Karaoke night": "Sing your favorite songs at a karaoke night with friends.",
    "Art and crafts": "Engage in art and crafts activities, such as painting or pottery.",
    "Wine tasting": "Visit a winery and enjoy wine tasting experiences.",
    "Photography outing": "Go on a photography outing and capture beautiful moments.",
    "Coffee meet-up": "Meet up with friends for coffee and conversations.",
    "Gardening": "Spend time gardening and tending to plants.",
    "Game night": "Gather with friends for a fun-filled game night.",
    "Cookout": "Organize a cookout or BBQ gathering with friends and family.",
    "Shopping spree": "Indulge in a shopping spree and explore different stores.",
    "Camping trip": "Go camping and immerse yourself in the beauty of nature.",
    "Movie marathon": "Have a movie marathon at home with your favorite films.",
    "Wine and paint night": "Attend a wine and paint night and create your own artwork.",
    "Food festival": "Visit a food festival and savor delicious cuisines.",
    "Cycling tour": "Embark on a cycling tour and explore scenic routes.",
    "Outdoor adventure park": "Visit an outdoor adventure park and enjoy thrilling activities.",
    "Cooking competition": "Participate in a cooking competition and showcase your culinary skills.",
    "Live comedy show": "Laugh out loud at a live comedy show or stand-up performance.",
    "Craft beer tasting": "Experience craft beer tasting and explore different flavors.",
    "City sightseeing": "Go on a city sightseeing tour and discover landmarks and attractions.",
    "Escape room challenge": "Test your problem-solving skills in an escape room challenge.",
    "Fishing trip": "Enjoy a fishing trip and relax by the water.",
    "Music festival": "Attend a music festival and listen to your favorite bands.",
    "Salsa dancing": "Learn salsa dancing and groove to Latin rhythms.",
    "Paintball game": "Engage in an exciting paintball game with friends.",
    "Outdoor photography workshop": "Join an outdoor photography workshop and improve your skills.",
    "Potluck dinner": "Organize a potluck dinner and share homemade dishes.",
    "Farmers market visit": "Explore a farmers market"
  },
  EX: {
    "Dance party": "Organize or attend a lively dance party where people can socialize, dance, and enjoy energetic music.",
    "Networking event": "Attend networking events to meet new people, make connections, and engage in professional or personal networking opportunities.",
    "Karaoke night": "Participate in a karaoke night where individuals can showcase their singing talents and enjoy a lively and interactive atmosphere.",
    "Social sports": "Join social sports leagues or teams, such as soccer, basketball, or volleyball, to engage in competitive yet social activities with other like-minded individuals.",
    "Group fitness classes": "Participate in group fitness classes like Zumba, aerobics, or group cycling, where individuals can exercise in a dynamic and sociable environment.",
    "Speed dating": "Take part in speed dating events where individuals can meet and interact with potential romantic partners in a fast-paced and social setting.",
    "Improv workshop": "Attend improv workshops or classes that focus on spontaneous and interactive acting exercises, encouraging extroverted individuals to express themselves creatively.",
    "Trivia night": "Join a trivia night at a local pub or restaurant, where teams compete in answering trivia questions and enjoy a lively and social atmosphere.",
    "Meetup groups": "Join various meetup groups that align with specific interests or hobbies to connect with like-minded individuals and engage in social activities together.",
    "Group travel": "Organize or join group travel experiences where extroverted individuals can explore new destinations, meet fellow travelers, and engage in group activities.",
    "Volunteer for community events": "Get involved in volunteering for community events, festivals, or charity initiatives, which provide opportunities to meet new people and contribute to a cause.",
    "Public speaking engagements": "Seek opportunities to participate in public speaking engagements, such as giving presentations or hosting events, where extroverts can showcase their communication skills and engage with an audience.",
    "Social club memberships": "Join social clubs or organizations that host regular gatherings, parties, or events for individuals to socialize and connect with others who share similar interests.",
    "Group dining experiences": "Organize or attend group dining experiences, such as food tours, cooking classes, or themed dinners, where extroverts can enjoy good food and engage in lively conversations with fellow food enthusiasts.",
    "Concerts or music festivals": "Attend concerts or music festivals, which provide energetic and social environments where individuals can enjoy live music performances and connect with other music enthusiasts.",
    "Comedy shows or improv performances": "Experience comedy shows or improv performances that offer opportunities for extroverted individuals to laugh, engage with performers, and enjoy interactive comedic experiences.",
    "Party planning": "Engage in organizing parties or social events, where extroverted individuals can bring people together and create memorable experiences for guests.",
    "Social mixers or happy hours": "Attend social mixers, networking happy hours, or after-work events to meet new people, socialize, and build connections in a relaxed and social atmosphere.",
    "Hobby or interest-based groups": "Join hobby or interest-based groups, clubs, or classes where extroverted individuals can connect with others who share similar passions and enjoy socializing while pursuing their interests.",
    "Team-building activities": "Participate in team-building activities, such as escape rooms, outdoor adventures, or group challenges, where extroverts can collaborate, communicate, and connect with others in a fun and social setting."
  },
  IN: {
    "Solo movie night": "Enjoy a cozy movie night at home, watching your favorite films or exploring new ones.",
    "Journaling": "Spend time writing in a journal to reflect on your thoughts, emotions, and experiences.",
    "Nature walks": "Take peaceful walks in nature, immersing yourself in the calming environment.",
    "Artistic hobbies": "Engage in artistic hobbies such as painting, drawing, or crafting, which allow for self-expression and relaxation.",
    "Reading": "Indulge in reading books, novels, or articles that spark your interest and provide an escape into different worlds.",
    "Cooking or baking": "Find solace in the kitchen by trying out new recipes or experimenting with your favorite dishes.",
    "Yoga or meditation": "Practice yoga or meditation to promote relaxation, mindfulness, and self-care.",
    "Online courses": "Enroll in online courses or educational platforms to learn at your own pace and explore new subjects of interest.",
    "Virtual socializing": "Engage in virtual social activities, such as online gaming, forums, or virtual book clubs, where you can connect with others from the comfort of your own space.",
    "Crafting": "Explore various crafting activities, such as knitting, origami, or scrapbooking, to engage in creative and calming endeavors.",
    "Listen to music or podcasts": "Enjoy the therapeutic effects of music or immerse yourself in interesting podcasts or audiobooks.",
    "Gardening": "Spend time nurturing plants and creating a peaceful garden space to connect with nature.",
    "Photography": "Capture moments and express your creativity through photography, focusing on subjects that interest you.",
    "Puzzles and brainteasers": "Challenge your mind and enhance your problem-solving skills with puzzles, crosswords, or brain-teaser games.",
    "Cooking at home": "Find joy in cooking meals at home, experimenting with flavors and creating comforting dishes.",
    "Home workouts": "Engage in home workouts, such as yoga or bodyweight exercises, to promote physical and mental well-being.",
    "Online writing communities": "Connect with other writers in online writing communities or forums, sharing your work and receiving feedback in a supportive environment.",
    "DIY projects": "Embark on DIY projects around the house, exploring your creativity and improving your living space.",
    "Self-care routines": "Create personalized self-care routines that focus on relaxation, skincare, or pampering yourself.",
    "Virtual museum tours": "Explore museums and art galleries through virtual tours, appreciating art and history from the comfort of your home.",
    "Soothing hobbies": "Engage in soothing hobbies such as knitting, crocheting, or coloring books, which promote relaxation and focus.",
    "Podcast creation": "Express your thoughts and interests by creating your own podcast, sharing your ideas with a virtual audience.",
    "Home organization": "Organize and declutter your living space, creating a serene and peaceful environment.",
    "Sensory activities": "Explore sensory activities such as aromatherapy, sensory bins, or tactile play, providing soothing experiences for relaxation.",
    "Star gazing": "Spend time observing the night sky and connecting with the wonders of the universe.",
    "Virtual museum visits": "Take virtual tours of museums and art exhibitions, allowing you to explore culture and history at your own pace.",
    "Writing fiction": "Escape into the world of fiction by writing stories, creating characters, and immersing yourself in your own narratives.",
    "Indoor gardening": "Nurture indoor plants, creating a mini garden that brings nature into your home",
  }

};

const Essays = {
  'The necessity of community':
    `We did not develop to live alone. The very fact we humans experience loneliness is as a direct result of us being herd animals, community animals. When we first evolved into our current species, and likely long before, we relied on one another for our survival, being isolated meant being dead. No single person can create anything close to what we have created as a collective. No single person can encompass the vast knowledge stored and spread across humanity. We are strong because we work together. Apes strong together, and we really are just great apes.
  <br>
  This feature of the human species gave rise to empathy, being able to relate to others and feel how they feel. Without empathy, everybody would use and abuse each other relentlessly. And yes these things happen despite our ability to empathize, however clearly a large part of us are really trying to do things right.
  <br>
  We are of course not the only species on this earth with empathy. There are many species who have learned to communicate, work together, and help each other. We are not inherently selfish, we are inherently empathetic and curious. It is a great failing of the modern education system and society as a whole that we are not taught how to help others and ask for help ourselves. 
  <br>
  Instead, we live as individuals, in separate houses, disconnected from the anonymous people we see each day. We are taught that we need to do everything individually, and that anyone who fails to be able to maintain every aspect of their own lives is dysfunctional, broken, or even bad. We walk around houseless people passed out on the street judging them for making “bad choices”, assuming its someone elses job to “take care of them” or even wishing them gone altogether. 
  <br>
  But in a capitalistic society like the one we live in nobody will take care of anyone. Nobody really wants to do their jobs, they feel they have no other choice to survive. Nobody wants to pay taxes, and lose more of their hard earned income and stability. Everybody is taught to hoard their wealth, from the homeless person to the billionaire. Everybody is taught to compete, dominate and control whomever they can, assert their will. Some are societally considered better people, and some worse. Common stereotypes and taboos run rampant, disconnecting people further. We are taught to obey, not how to figure things out together. This is a major flaw with life in this world. 
  <br>
  The thing is, none of us are “better” or “worse” than any other human on this planet. That’s right, youre no better than Hitler, but youre also not worse. People are flawed. ALL people. Women are not “more emotional” than men, we’ve just been trained to express it differently. A man is equally likely to mess up, to get heated and impulsive and aggressive to any woman. 
  <br>
  We are in fact all different, and all the same. Every human is a different mix of likes, dislikes, appearances personalities. There are “manly” women, and womanly men, and trans people, and nonbinary people, as much as you try and deny their existence they are as real and valid humans as anyone else. There is any variation of human you can imagine in existence at any given point, theres 8 billion of us, a number completely incomprehensible. 
  <br>
  And each one of those humans can be or become disabled at any point in there life, and almost everyone does, at the very least when they grow old. As children we are all dependents on others care and help to survive, why is it such a strange concept that when we grow into adults we dont suddenly become completely independent of others. 
  <br>
  We are never completely independent in this society, we are simply disconnected from just how much we depend on that homeless teenager, who may eventually provide great service to the world, with the right support to get them out of that situation. 
  <br>
  Expecting people to pull themselves up by their bootstraps, much like the expression itself is impossible and severely misinformed. A person from a privileged position may come to believe they made the right decisions and therefore are a good person, better than the drug addict on the corner of the street, when in fact the only difference is the support you received that they didn’t get. 
  <br>
  Certainly some people require higher levels of support, but what a strange world we live in that a need for help is punished. Anyone can become homeless, you, your mother, your 5th cousin who has a PHD in neuroscience, the neighbor who owns a boat, thinking yourself above people who struggle is an incredibly heartless and inconsiderate thing to do, especially knowing you could very well be in their position in need of that support. 
  <br>
  Just because you currently have funds or friends does not absolve you from being a member of the same society where people needlessly starve and freeze on the streets while 1/3rd of all food produced heads straight to the dumpster, and millions of houses stand empty. If every church in the USA helped one foster child and 75% helped one homeless person, there would be no one left to help. These congregations of hundreds preaching to treat your neighbor as yourself, who have however not managed to help anyone. 
  <br>
  So, with the understanding that organized religion and our government refuse to support all their citizens properly, we must take things into our own hands and organize. 
  <br>
  This app was intended to create an open market for people to express their support needs and capabilities. We are under the firm belief that every human is valuable no matter what or how much they provide the society at large, because our most vulnerable are those who cannot provide and thereby arent valued by the current society and system. 
  <br>
  Everybody can provide services, even just an ear to listen, a shared experience, or whatever else. It is also clear that helping others when you are capable makes life far more fulfilling, and the more you help the more others will be able to help and function in their own ways to enrich our society through any number of ways we cannot even imagine as single humans with knowledge and understanding limited to one brain and one persons lived experiences. We all benefit from helping and being helped, and it appears to us that there are systems in place to actively hinder our ability to do so, and actively create discord to make enemies of each other. 
  <br>
  Life doesn’t have to be about competition, it could be about cooperation and everyone would be better off for it. We wouldnt need to hoard our wealth because we know it was actually being used to help people, and everyone could get the support they need without having to prove themselves as more than just alive- because every living person deserves the help they need to have a bearable existence.  <br>
  <br>
  `,
};