
function getAnimalDetails() {
	const animalDetails = {
		Aardvark: {
			name: "Aardvark",
			lifespan: "23 years",
			habitat: "Savannahs, grasslands, woodlands",
			avgGrownupWeight: "60 kg",
			avgSize: "1.3 m",
			preferredFood: "Ants and termites",
			species: "Orycteropus afer",
			color: "Pale yellow or grey",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1",
			class: "Mammal"
		},
		alpaca: {
			name: "Alpaca",
			lifespan: "15-20 years",
			habitat: "Mountainous regions of South America",
			avgGrownupWeight: "55-65 kg",
			avgSize: "90-100 cm tall",
			preferredFood: "Grasses, hay, and sometimes grains",
			species: "Vicugna pacos",
			color: "Various colors including white, brown, and black",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1 cria (baby alpaca)",
			class: "Mammal"
		},
		ant: {
			name: "Ant",
			lifespan: "Several weeks to several years depending on species",
			habitat: "Various terrestrial habitats including forests, grasslands, and urban areas",
			avgGrownupWeight: "0.1-5 mg depending on species",
			avgSize: "1-50 mm depending on species",
			preferredFood: "Omnivorous: scavenges for dead insects, nectar, seeds, fungi",
			species: "Formicidae family",
			color: "Varies by species: black, brown, red, or yellow",
			reproduction: "Egg-laying",
			avgNumberOfOffsprings: "Varies by species: from a few to thousands of eggs per queen",
			class: "Insect"
		},
		Armadillo: {
			name: "Armadillo",
			lifespan: "4-30 years, depending on species",
			habitat: "Grasslands, forests, and semi-deserts",
			avgGrownupWeight: "0.5-6 kg, depending on species",
			avgSize: "15-75 cm, depending on species",
			preferredFood: "Insects, small vertebrates, plants",
			species: "Dasypodidae",
			color: "Brown, grey, or pinkish",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1-12, depending on species",
			class: "Mammal"
		},
		badger: {
			name: "Badger",
			lifespan: "4-10 years in the wild, up to 14 years in captivity",
			habitat: "Forests, grasslands, deserts",
			avgGrownupWeight: "5-15 kg",
			avgSize: "0.6-0.9 m long",
			preferredFood: "Omnivorous: insects, small mammals, birds, fruits, roots",
			species: "Meles and Taxidea genera",
			color: "Gray to black with distinctive white facial markings",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1-5 cubs per litter",
			class: "Mammal"
		},
		Beaver: {
			name: "Beaver",
			lifespan: "10-15 years in the wild, up to 20 years in captivity",
			habitat: "Rivers, streams, lakes, and ponds",
			avgGrownupWeight: "16-32 kg",
			avgSize: "0.9-1.4 m long including tail",
			preferredFood: "Herbivorous: bark, twigs, leaves, aquatic plants",
			species: "Castor genus",
			color: "Brown fur with webbed hind feet and flat tail",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "2-4 kits per litter",
			class: "Mammal"
		},
		bee: {
			name: "Bee",
			lifespan: "4-6 weeks for worker bees, several months for queen bees",
			habitat: "Varied habitats including gardens, meadows, and forests",
			avgGrownupWeight: "Approximately 100 mg",
			avgSize: "10-20 mm depending on species",
			preferredFood: "Herbivorous: collects pollen and nectar from flowers",
			species: "Anthophila order",
			color: "Varies by species: yellow and black stripes, or metallic green or blue",
			reproduction: "Egg-laying",
			avgNumberOfOffsprings: "Varies by species: up to thousands of eggs per queen",
			class: "Insect"
		},
		bison: {
			name: "Bison",
			lifespan: "15-20 years",
			habitat: "Grasslands, prairies, forests",
			avgGrownupWeight: "500-1000 kg",
			avgSize: "1.5-2 m tall at the shoulder",
			preferredFood: "Grasses, herbs, shrubs",
			species: "Bison bison (American bison)",
			color: "Dark brown to black",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1 calf",
			class: "Mammal"
		},
		blue_morpho_butterfly: {
			name: "Blue Morpho Butterfly",
			lifespan: "2-3 weeks as adults",
			habitat: "Tropical rainforests of Central and South America",
			avgGrownupWeight: "0.5-0.7 g",
			avgSize: "12-20 cm wingspan",
			preferredFood: "Herbivorous: primarily feeds on rotting fruits, tree sap, and nectar",
			species: "Morpho genus",
			color: "Iridescent blue wings with brown undersides",
			reproduction: "Egg-laying",
			avgNumberOfOffsprings: "Hundreds of eggs laid individually on host plants",
			class: "Insect"
		},
		Bobcat: {
			name: "Bobcat",
			lifespan: "10-12 years in the wild, up to 25 years in captivity",
			habitat: "Forests, swamps, deserts, and urban areas",
			avgGrownupWeight: "6-12 kg",
			avgSize: "0.5-0.8 m long",
			preferredFood: "Carnivorous: small mammals, birds, rabbits, and rodents",
			species: "Lynx rufus",
			color: "Spotted or streaked coat, usually brownish-red to grayish-brown",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1-6 kittens per litter",
			class: "Mammal"
		},
		buffalo: {
			name: "Buffalo",
			lifespan: "10-20 years",
			habitat: "Grasslands, savannas, woodlands",
			avgGrownupWeight: "500-900 kg",
			avgSize: "1.5-1.8 m tall at the shoulder",
			preferredFood: "Grasses, herbs, shrubs",
			species: "Syncerus caffer (Cape buffalo)",
			color: "Dark brown to black",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1 calf",
			class: "Mammal"
		},
		Bumblebee: {
			name: "Bumblebee",
			lifespan: "4-6 weeks for worker bees, several months for queen bees",
			habitat: "Varied habitats including gardens, meadows, and forests",
			avgGrownupWeight: "Approximately 300 mg",
			avgSize: "10-23 mm depending on species",
			preferredFood: "Herbivorous: collects pollen and nectar from flowers",
			species: "Bombus genus",
			color: "Varies by species: black and yellow stripes, or orange and black",
			reproduction: "Egg-laying",
			avgNumberOfOffsprings: "Varies by species: up to hundreds of eggs per queen",
			class: "Insect"
		},
		camel: {
			name: "Camel",
			lifespan: "40-50 years",
			habitat: "Deserts, arid regions",
			avgGrownupWeight: "400-600 kg",
			avgSize: "1.8-2.2 m tall at the shoulder",
			preferredFood: "Grasses, grains, leaves",
			species: "Camelus",
			color: "Light brown to dark brown",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1 calf",
			class: "Mammal"
		},
		Capybara: {
			name: "Capybara",
			lifespan: "8-10 years in the wild, up to 12 years in captivity",
			habitat: "Semi-aquatic: rivers, lakes, marshes, and forests",
			avgGrownupWeight: "35-65 kg",
			avgSize: "0.5-0.6 m tall at the shoulder",
			preferredFood: "Herbivorous: grasses, aquatic plants, fruits",
			species: "Hydrochoerus hydrochaeris",
			color: "Brownish-gray fur with a stout body and webbed feet",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "2-8 pups per litter",
			class: "Mammal"
		},
		cheetah: {
			name: "Cheetah",
			lifespan: "10-12 years",
			habitat: "Grasslands, savannas",
			avgGrownupWeight: "50 kg",
			avgSize: "1.2 m",
			preferredFood: "Gazelles, wildebeests calves, impalas",
			species: "Acinonyx jubatus",
			color: "Golden with black spots",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "3-5",
			class: "Mammal"
		},
		chimpanzee: {
			name: "Chimpanzee",
			lifespan: "33-40 years",
			habitat: "Tropical forests",
			avgGrownupWeight: "40-70 kg",
			avgSize: "1.2 m",
			preferredFood: "Fruit, nuts, seeds, insects",
			species: "Pan troglodytes",
			color: "Black",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1",
			class: "Mammal"
		},
		Cockroach: {
			name: "Cockroach",
			lifespan: "6 months to 2 years depending on species",
			habitat: "Found worldwide in warm environments, often in homes and buildings",
			avgGrownupWeight: "3-50 g depending on species",
			avgSize: "10-50 mm depending on species",
			preferredFood: "Omnivorous: scavenges on organic matter, food scraps, and even glue",
			species: "Blattodea order",
			color: "Varies by species: typically brown or black",
			reproduction: "Egg-laying",
			avgNumberOfOffsprings: "Varies by species: can produce several hundred to thousands of eggs",
			class: "Insect"
		},
		cricket: {
			name: "Cricket",
			lifespan: "1-2 years depending on species",
			habitat: "Grasslands, forests, and urban areas",
			avgGrownupWeight: "0.5-3 g depending on species",
			avgSize: "2-5 cm",
			preferredFood: "Omnivorous: eats plants, fungi, and occasionally other insects",
			species: "Gryllidae family",
			color: "Varies by species: typically brown or black",
			reproduction: "Egg-laying",
			avgNumberOfOffsprings: "Up to 150 eggs laid in soil or vegetation",
			class: "Insect"
		},
		Earwig: {
			name: "Earwig",
			lifespan: "1-3 years depending on species",
			habitat: "Moist areas such as gardens, under rocks, and in rotting wood",
			avgGrownupWeight: "0.1-1 g depending on species",
			avgSize: "10-50 mm including pincers",
			preferredFood: "Omnivorous: feeds on plants, insects, and decaying organic matter",
			species: "Dermaptera order",
			color: "Dark brown or black with reddish-brown appendages",
			reproduction: "Egg-laying",
			avgNumberOfOffsprings: "Up to 80 eggs laid in soil or debris",
			class: "Insect"
		},
		elephant: {
			name: "Elephant",
			lifespan: "60-70 years",
			habitat: "Savannah and forest",
			avgGrownupWeight: "6000 kg",
			avgSize: "3 m",
			preferredFood: "Grass, leaves",
			species: "Loxodonta",
			color: "Grey",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1",
			class: "Mammal"
		},
		flamingo: {
			name: "Flamingo",
			lifespan: "20-30 years in the wild, up to 60 years in captivity",
			habitat: "Shallow lakes, lagoons, and coastal mudflats",
			avgGrownupWeight: "2-4 kg",
			avgSize: "1.1-1.5 m tall",
			preferredFood: "Algae, crustaceans, small fish",
			species: "Phoenicopteridae",
			color: "Pink to reddish-orange",
			reproduction: "Oviparous",
			avgNumberOfOffsprings: "1 chick",
			class: "Bird"
		},
		flea: {
			name: "Flea",
			lifespan: "2-3 months",
			habitat: "Found worldwide, often in homes, on pets, and in wildlife habitats",
			avgGrownupWeight: "Varies by species, typically less than 1 mg",
			avgSize: "1-4 mm",
			preferredFood: "Parasitic: blood of mammals and birds",
			species: "Siphonaptera order",
			color: "Dark brown to reddish-brown",
			reproduction: "Egg-laying",
			avgNumberOfOffsprings: "Several hundred eggs laid in bedding or host animal fur",
			class: "Insect"
		},
		fire_ant: {
			name: "Fire Ant",
			lifespan: "1-3 years",
			habitat: "Mostly in warm climates, often found in urban areas and agricultural lands",
			avgGrownupWeight: "0.5-6 mg depending on species",
			avgSize: "2-6 mm",
			preferredFood: "Omnivorous: feeds on plant matter, seeds, insects, and other small animals",
			species: "Solenopsis genus",
			color: "Reddish-brown to black",
			reproduction: "Egg-laying",
			avgNumberOfOffsprings: "Varies by colony size: can produce thousands of eggs per queen",
			class: "Insect"
		},
		fox: {
			name: "Fox",
			lifespan: "2-5 years in the wild, up to 15 years in captivity",
			habitat: "Varied habitats including forests, grasslands, mountains, and urban areas",
			avgGrownupWeight: "3-14 kg depending on species",
			avgSize: "0.3-0.5 m tall at the shoulder",
			preferredFood: "Small mammals, birds, insects, fruits, and berries",
			species: "Vulpes genus",
			color: "Red, gray, brown, white, or black depending on species",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "4-5 pups per litter",
			class: "Mammal"
		},
		giraffe: {
			name: "Giraffe",
			lifespan: "20-25 years",
			habitat: "Savannah",
			avgGrownupWeight: "1200 kg",
			avgSize: "4.8 m",
			preferredFood: "Leaves, twigs",
			species: "Giraffa camelopardalis",
			color: "Yellow with brown spots",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1",
			class: "Mammal"
		},
		gorilla: {
			name: "Gorilla",
			lifespan: "35-40 years",
			habitat: "Forests",
			avgGrownupWeight: "160 kg",
			avgSize: "1.7 m",
			preferredFood: "Leaves, shoots, fruit",
			species: "Gorilla beringei",
			color: "Black, grey",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1",
			class: "Mammal"
		},
		Grasshopper: {
			name: "Grasshopper",
			lifespan: "1 year or more depending on species",
			habitat: "Grasslands, meadows, and agricultural fields",
			avgGrownupWeight: "Up to 2 g depending on species",
			avgSize: "2-11 cm depending on species",
			preferredFood: "Herbivorous: primarily eats grasses, leaves, and crops",
			species: "Caelifera suborder",
			color: "Varies by species: typically green, brown, or gray camouflage",
			reproduction: "Egg-laying",
			avgNumberOfOffsprings: "Varies by species: can lay dozens to hundreds of eggs",
			class: "Insect"
		},
		Hedgehog: {
			name: "Hedgehog",
			lifespan: "2-5 years in the wild, up to 7 years in captivity",
			habitat: "Forests, grasslands, urban gardens",
			avgGrownupWeight: "0.4-1.2 kg",
			avgSize: "15-30 cm long",
			preferredFood: "Insectivorous: insects, worms, small vertebrates",
			species: "Erinaceidae family",
			color: "Spiny coat ranging from brown to white",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "2-7 hoglets per litter",
			class: "Mammal"
		},
		hippopotamus: {
			name: "Hippopotamus",
			lifespan: "40-50 years",
			habitat: "Rivers, lakes",
			avgGrownupWeight: "1500 kg",
			avgSize: "1.5 m at the shoulder",
			preferredFood: "Grasses",
			species: "Hippopotamus amphibius",
			color: "Greyish",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1",
			class: "Mammal"
		},
		hyena: {
			name: "Hyena",
			lifespan: "10-25 years",
			habitat: "Savannas, grasslands, and woodlands",
			avgGrownupWeight: "50-80 kg",
			avgSize: "0.7-1.3 m tall at the shoulder",
			preferredFood: "Scavenger: carrion, but also hunt small to medium-sized animals",
			species: "Hyaenidae family",
			color: "Spotted or striped coats, varying in color from light grey to dark brown",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1-3 cubs per litter",
			class: "Mammal"
		},
		ibex: {
			name: "Ibex",
			lifespan: "10-15 years",
			habitat: "Mountainous regions, cliffs, and rocky slopes",
			avgGrownupWeight: "30-120 kg depending on species",
			avgSize: "0.8-1.2 m tall at the shoulder",
			preferredFood: "Herbivorous: grasses, herbs, leaves",
			species: "Capra genus",
			color: "Brownish-gray fur with long, curved horns",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1 kid",
			class: "Mammal"
		},
		Imago: {
			name: "Imago",
			lifespan: "Several days to several weeks depending on species",
			habitat: "Varied habitats depending on the insect species",
			avgGrownupWeight: "Varies by species",
			avgSize: "Varies by species",
			preferredFood: "Varies by species: could be nectar, pollen, or other plant parts",
			species: "Varies by insect species",
			color: "Varies by species",
			reproduction: "Varies by species: can reproduce sexually or asexually",
			avgNumberOfOffsprings: "Varies by species",
			class: "Insect"
		},
		kangaroo: {
			name: "Kangaroo",
			lifespan: "20 years",
			habitat: "Grasslands, forests, savannahs",
			avgGrownupWeight: "85 kg",
			avgSize: "1.6 m",
			preferredFood: "Grasses, leaves",
			species: "Macropus",
			color: "Brown, grey",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1",
			class: "Mammal"
		},
		Katydid: {
			name: "Katydid",
			lifespan: "1-2 years depending on species",
			habitat: "Tropical and temperate regions, often in trees and shrubs",
			avgGrownupWeight: "1-5 g depending on species",
			avgSize: "2-6 cm depending on species",
			preferredFood: "Herbivorous: primarily eats leaves, flowers, and fruits",
			species: "Tettigoniidae family",
			color: "Varies by species: green, brown, or leaf-like camouflage",
			reproduction: "Egg-laying",
			avgNumberOfOffsprings: "Varies by species: can lay dozens to hundreds of eggs",
			class: "Insect"
		},
		koala: {
			name: "Koala",
			lifespan: "13-18 years",
			habitat: "Forest",
			avgGrownupWeight: "14 kg",
			avgSize: "85 cm",
			preferredFood: "Eucalyptus leaves",
			species: "Phascolarctos cinereus",
			color: "Grey",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1",
			class: "Mammal"
		},
		ladybug: {
			name: "Ladybug",
			lifespan: "1-2 years",
			habitat: "Gardens, meadows, forests, and agricultural fields",
			avgGrownupWeight: "Approximately 10 mg",
			avgSize: "5-8 mm",
			preferredFood: "Carnivorous: aphids, scale insects, and other small insects",
			species: "Coccinellidae family",
			color: "Red or orange with black spots, or black with red spots",
			reproduction: "Egg-laying",
			avgNumberOfOffsprings: "Up to hundreds of eggs",
			class: "Insect"
		},
		leopard: {
			name: "Leopard",
			lifespan: "12-17 years",
			habitat: "Forests, savannas, mountains, and grasslands",
			avgGrownupWeight: "60 kg",
			avgSize: "1.3 m",
			preferredFood: "Deer, antelopes, rodents",
			species: "Panthera pardus",
			color: "Golden with black spots",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "2-3",
			class: "Mammal"
		},
		lion: {
			name: "Lion",
			lifespan: "10-14 years in the wild, up to 20 years in captivity",
			habitat: "Grasslands, savannas, dense scrub, and open woodlands",
			avgGrownupWeight: "190 kg for males, 130 kg for females",
			avgSize: "1.2 m at the shoulder",
			preferredFood: "Large ungulates such as zebras, antelopes, and wildebeests",
			species: "Panthera leo",
			color: "Tawny yellow coat",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "2-3 cubs",
			class: "Mammal"
		},
		llama: {
			name: "Llama",
			lifespan: "15-25 years",
			habitat: "Mountainous regions of South America",
			avgGrownupWeight: "130-200 kg",
			avgSize: "1.7-1.8 m tall",
			preferredFood: "Grasses, hay, and occasionally grains",
			species: "Lama glama",
			color: "Various colors including white, brown, and black",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1 cria (baby llama)",
			class: "Mammal"
		},
		lynx: {
			name: "Lynx",
			lifespan: "10-15 years in the wild, up to 25 years in captivity",
			habitat: "Forests, tundra, and mountainous regions",
			avgGrownupWeight: "8-18 kg depending on species",
			avgSize: "0.5-0.8 m tall at the shoulder",
			preferredFood: "Carnivorous: small to medium-sized mammals, birds",
			species: "Lynx genus",
			color: "Light brown to gray fur with tufted ears and short tail",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1-4 kittens per litter",
			class: "Mammal"
		},
		meerkat: {
			name: "Meerkat",
			lifespan: "12-14 years in captivity",
			habitat: "Open, arid habitats like savannas and grasslands",
			avgGrownupWeight: "0.7-1 kg",
			avgSize: "25-35 cm",
			preferredFood: "Insects, small vertebrates, eggs, roots",
			species: "Suricata suricatta",
			color: "Greyish to tan with darker bands",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "2-5 pups per litter",
			class: "Mammal"
		},
		mongoose: {
			name: "Mongoose",
			lifespan: "6-10 years in the wild, up to 20 years in captivity",
			habitat: "Various habitats including forests, savannas, and grasslands",
			avgGrownupWeight: "0.3-5 kg depending on species",
			avgSize: "0.2-0.6 m long",
			preferredFood: "Omnivorous: insects, small mammals, birds, eggs, fruits",
			species: "Herpestidae family",
			color: "Brown, gray, or yellowish fur",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "2-4 pups per litter",
			class: "Mammal"
		},
		Moth: {
			name: "Moth",
			lifespan: "1-2 months depending on species",
			habitat: "Varied habitats including forests, gardens, and urban areas",
			avgGrownupWeight: "Varies by species, typically less than 1 g",
			avgSize: "1-5 cm wingspan depending on species",
			preferredFood: "Herbivorous: larvae feed on plant material, adults primarily seek nectar",
			species: "Lepidoptera order",
			color: "Varies by species: wide range of colors and patterns",
			reproduction: "Egg-laying",
			avgNumberOfOffsprings: "Varies by species: can lay hundreds of eggs",
			class: "Insect"
		},
		Narwhal: {
			name: "Narwhal",
			lifespan: "50-60 years",
			habitat: "Arctic waters near Canada, Greenland, and Russia",
			avgGrownupWeight: "1,500-1,800 kg",
			avgSize: "4-5 m long, including tusk",
			preferredFood: "Carnivorous: fish, squid, shrimp",
			species: "Monodon monoceros",
			color: "Mottled grayish-brown skin with a distinctive spiral tusk",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1 calf",
			class: "Mammal"
		},
		Orangutan: {
			name: "Orangutan",
			lifespan: "35-45 years in the wild, up to 55 years in captivity",
			habitat: "Tropical rainforests of Borneo and Sumatra",
			avgGrownupWeight: "30-90 kg depending on species",
			avgSize: "1.2-1.5 m tall",
			preferredFood: "Primarily frugivorous: fruits, leaves, insects",
			species: "Pongo genus",
			color: "Orange to reddish-brown fur",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1 infant",
			class: "Mammal"
		},
		ostrich: {
			name: "Ostrich",
			lifespan: "30-40 years",
			habitat: "Savannas, grasslands, and semi-desert areas",
			avgGrownupWeight: "100-130 kg",
			avgSize: "2-2.8 m tall",
			preferredFood: "Plants, seeds, and occasionally insects",
			species: "Struthio camelus",
			color: "Mainly brown and white",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "4-8 eggs per clutch",
			class: "Bird"
		},
		otter: {
			name: "Otter",
			lifespan: "10-15 years in the wild, up to 25 years in captivity",
			habitat: "Rivers, lakes, coastal areas",
			avgGrownupWeight: "5-14 kg",
			avgSize: "0.6-1.3 m long",
			preferredFood: "Carnivorous: fish, crustaceans, amphibians",
			species: "Lutrinae family",
			color: "Brown fur with lighter underparts",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1-5 pups per litter",
			class: "Mammal"
		},
		panda: {
			name: "Panda",
			lifespan: "20 years",
			habitat: "Temperate broadleaf and mixed forests",
			avgGrownupWeight: "100 kg",
			avgSize: "1.5 m",
			preferredFood: "Bamboo",
			species: "Ailuropoda melanoleuca",
			color: "Black and white",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1-2",
			class: "Mammal"
		},
		penguin: {
			name: "Penguin",
			lifespan: "15-20 years",
			habitat: "Marine and coastal",
			avgGrownupWeight: "25 kg",
			avgSize: "70 cm",
			preferredFood: "Fish, squid",
			species: "Aptenodytes forsteri",
			color: "Black and white",
			reproduction: "Oviparous",
			avgNumberOfOffsprings: "2",
			class: "Bird"
		},
		Platypus: {
			name: "Platypus",
			lifespan: "15-20 years in the wild, up to 17 years in captivity",
			habitat: "Freshwater rivers, streams, and lakes in eastern Australia and Tasmania",
			avgGrownupWeight: "0.7-2.4 kg",
			avgSize: "30-40 cm long",
			preferredFood: "Carnivorous: aquatic insects, larvae, and small crustaceans",
			species: "Ornithorhynchus anatinus",
			color: "Dark brown fur with a duck-like bill and webbed feet",
			reproduction: "Oviparous (egg-laying)",
			avgNumberOfOffsprings: "1-3 eggs per clutch",
			class: "Mammal"
		},
		Porcupine: {
			name: "Porcupine",
			lifespan: "15-20 years",
			habitat: "Forests, deserts, and grasslands",
			avgGrownupWeight: "18 kg",
			avgSize: "80 cm",
			preferredFood: "Bark, leaves, fruit",
			species: "Erethizon dorsatum",
			color: "Brown or black with sharp spines",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1-2",
			class: "Mammal"
		},
		raccoon: {
			name: "Raccoon",
			lifespan: "2-3 years in the wild, up to 20 years in captivity",
			habitat: "Forests, wetlands, urban areas",
			avgGrownupWeight: "5-12 kg",
			avgSize: "0.3-0.6 m long",
			preferredFood: "Omnivorous: fruits, nuts, insects, small vertebrates, eggs, garbage",
			species: "Procyon lotor",
			color: "Grayish-brown fur with black facial mask and ringed tail",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "2-5 kits per litter",
			class: "Mammal"
		},
		red_panda: {
			name: "Red Panda",
			lifespan: "8-12 years in the wild, up to 14 years in captivity",
			habitat: "Temperate forests in the Himalayas",
			avgGrownupWeight: "3-6 kg",
			avgSize: "0.5-0.6 m long including tail",
			preferredFood: "Herbivorous: bamboo leaves, berries, fruits",
			species: "Ailurus fulgens",
			color: "Reddish-brown fur with white face markings and ringed tail",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1-4 cubs per litter",
			class: "Mammal"
		},
		rhinoceros: {
			name: "Rhinoceros",
			lifespan: "35-50 years",
			habitat: "Grasslands, savannahs",
			avgGrownupWeight: "2300 kg",
			avgSize: "1.8 m",
			preferredFood: "Grasses, leaves, branches",
			species: "Rhinocerotidae",
			color: "Grey",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1",
			class: "Mammal"
		},
		sea_lion: {
			name: "Sea Lion",
			lifespan: "20-30 years",
			habitat: "Marine",
			avgGrownupWeight: "300 kg",
			avgSize: "2.5 m",
			preferredFood: "Fish, squid",
			species: "Zalophus californianus",
			color: "Brown",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1",
			class: "Mammal"
		},
		seal: {
			name: "Seal",
			lifespan: "20-30 years",
			habitat: "Coastal waters and ice floes of the Arctic and Antarctic",
			avgGrownupWeight: "85-300 kg depending on species",
			avgSize: "1.5-3 m long",
			preferredFood: "Carnivorous: fish, squid, and crustaceans",
			species: "Phocidae family",
			color: "Varies by species: gray, brown, or spotted patterns",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1 pup",
			class: "Mammal"
		},
		Silverfish: {
			name: "Silverfish",
			lifespan: "2-8 years depending on species",
			habitat: "Dark and damp areas such as basements, kitchens, and bathrooms",
			avgGrownupWeight: "Up to 1 g",
			avgSize: "10-20 mm including antennae and tail",
			preferredFood: "Detritivorous: feeds on starches, cellulose, and sugars found in paper, books, and fabrics",
			species: "Lepisma saccharina",
			color: "Silvery-gray or bluish-silver scales covering elongated body",
			reproduction: "Egg-laying",
			avgNumberOfOffsprings: "Up to 60 eggs laid in cracks and crevices",
			class: "Insect"
		},
		skunk: {
			name: "Skunk",
			lifespan: "2-4 years in the wild, up to 10 years in captivity",
			habitat: "Forests, grasslands, urban areas",
			avgGrownupWeight: "1.5-4.5 kg",
			avgSize: "0.3-0.4 m long",
			preferredFood: "Omnivorous: insects, small vertebrates, fruits, plants",
			species: "Mephitidae family",
			color: "Black with white stripes down the back",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "2-10 kits per litter",
			class: "Mammal"
		},
		sloth: {
			name: "Sloth",
			lifespan: "20-30 years",
			habitat: "Tropical rainforests",
			avgGrownupWeight: "8 kg",
			avgSize: "60 cm",
			preferredFood: "Leaves, fruits, insects",
			species: "Bradypus",
			color: "Brown",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1",
			class: "Mammal"
		},
		stick_insect: {
			name: "Stick Insect",
			lifespan: "1-3 years depending on species",
			habitat: "Forests, grasslands, and gardens",
			avgGrownupWeight: "0.5-50 g depending on species",
			avgSize: "2-30 cm depending on species",
			preferredFood: "Herbivorous: primarily eats leaves and foliage",
			species: "Phasmatodea order",
			color: "Varies by species: brown, green, or mottled to blend with surroundings",
			reproduction: "Egg-laying",
			avgNumberOfOffsprings: "Varies by species: can lay hundreds of eggs",
			class: "Insect"
		},
		tapir: {
			name: "Tapir",
			lifespan: "25-30 years",
			habitat: "Rainforests, grasslands, and mountains",
			avgGrownupWeight: "300 kg",
			avgSize: "2 m",
			preferredFood: "Leaves, twigs, fruit",
			species: "Tapirus",
			color: "Varies (typically dark brown, black, or grey)",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1",
			class: "Mammal"
		},
		termite: {
			name: "Termite",
			lifespan: "Several years depending on the caste",
			habitat: "Woodlands, forests, and urban areas",
			avgGrownupWeight: "Varies by species and caste, typically less than 1 g for workers",
			avgSize: "3-20 mm depending on species and caste",
			preferredFood: "Cellulose-rich materials like wood, paper, and plant debris",
			species: "Isoptera order",
			color: "Varies by species: white, cream, brown, or black",
			reproduction: "Egg-laying",
			avgNumberOfOffsprings: "Millions of eggs per colony, laid by the queen",
			class: "Insect"
		},
		tiger: {
			name: "Tiger",
			lifespan: "10-15 years",
			habitat: "Forest",
			avgGrownupWeight: "200 kg",
			avgSize: "3 m",
			preferredFood: "Deer, wild boars",
			species: "Panthera tigris",
			color: "Orange with black stripes",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "2-4",
			class: "Mammal"
		},
		Walrus: {
			name: "Walrus",
			lifespan: "20-30 years in the wild, up to 40 years in captivity",
			habitat: "Arctic and subarctic regions, often found on ice floes",
			avgGrownupWeight: "800-1,700 kg",
			avgSize: "2.2-3.6 m long",
			preferredFood: "Carnivorous: benthic invertebrates such as clams and snails",
			species: "Odobenus rosmarus",
			color: "Brown or pinkish skin with large tusks and whiskers",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1 calf",
			class: "Mammal"
		},
		Warthog: {
			name: "Warthog",
			lifespan: "15 years",
			habitat: "Grasslands, savanna, and woodlands",
			avgGrownupWeight: "100 kg",
			avgSize: "85 cm at the shoulder",
			preferredFood: "Grass, roots, berries",
			species: "Phacochoerus africanus",
			color: "Grey with sparse hair",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "2-6",
			class: "Mammal"
		},
		wolf: {
			name: "Wolf",
			lifespan: "6-8 years in the wild, up to 16 years in captivity",
			habitat: "Forests, mountains, grasslands, and arctic tundra",
			avgGrownupWeight: "20-80 kg depending on species",
			avgSize: "0.6-0.9 m tall at the shoulder",
			preferredFood: "Hunts large ungulates such as deer and elk, also small mammals",
			species: "Canis lupus",
			color: "Gray, brown, black, or white",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "4-6 pups per litter",
			class: "Mammal"
		},
		zebra: {
			name: "Zebra",
			lifespan: "25 years",
			habitat: "Grasslands, savannahs",
			avgGrownupWeight: "450 kg",
			avgSize: "1.3 m at the shoulder",
			preferredFood: "Grasses",
			species: "Equus quagga",
			color: "Black and white stripes",
			reproduction: "Viviparous",
			avgNumberOfOffsprings: "1",
			class: "Mammal"
		},


	};
	return animalDetails;
}

