var animalDetails = {
	sphynx_cat: {
		name: "Sphynx Cat",
		lifespan: "8-14 years",
		habitat: "Domestic",
		avgGrownupWeight: "3-5 kg",
		avgSize: "30-40 cm in length",
		preferredFood: "Carnivorous: commercial cat food, meat",
		species: "Felis catus",
		color: "Varies: often appears hairless with skin pigmentation",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "4-6 kittens per litter",
		class: "Mammal"
	},
	chameleon: {
		name: "Common Chameleon",
		lifespan: "2-10 years depending on species",
		habitat: "Tropical and subtropical forests, savannas",
		avgGrownupWeight: "100-200 g",
		avgSize: "15-25 cm",
		preferredFood: "Insectivorous: insects, small invertebrates",
		species: "Chamaeleo chamaeleon",
		color: "Varies: green, brown, can change color for camouflage and communication",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "20-40 eggs per clutch",
		class: "Reptile"
	},
	bengal_cat: {
		name: "Bengal Cat",
		lifespan: "12-16 years",
		habitat: "Domestic",
		avgGrownupWeight: "4-7 kg",
		avgSize: "35-45 cm in length",
		preferredFood: "Carnivorous: commercial cat food, meat",
		species: "Felis catus",
		color: "Spotted or marbled coat with a variety of colors",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "4-6 kittens per litter",
		class: "Mammal"
	},
	barn_owl: {
		name: "Barn Owl",
		lifespan: "4-10 years in the wild, up to 20 years in captivity",
		habitat: "Open countryside, farmlands, woodlands",
		avgGrownupWeight: "400-700 g",
		avgSize: "33-39 cm in length, wingspan 80-95 cm",
		preferredFood: "Carnivorous: small mammals, birds, insects",
		species: "Tyto alba",
		color: "Pale, heart-shaped face with a mix of white, golden-brown, and gray feathers",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "4-7 eggs per clutch",
		class: "Bird"
	},
	cattle_egret: {
		name: "Cattle Egret",
		lifespan: "10-15 years",
		habitat: "Grasslands, agricultural fields, wetlands",
		avgGrownupWeight: "300-400 g",
		avgSize: "46-56 cm in length, wingspan 88-96 cm",
		preferredFood: "Insectivorous: insects, especially grasshoppers, and other small invertebrates",
		species: "Bubulcus ibis",
		color: "White with yellow or orange bill and legs, can have buff patches during breeding season",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "3-4 eggs per clutch",
		class: "Bird"
	},
	main_coon_cat: {
		name: "Maine Coon Cat",
		lifespan: "12-15 years",
		habitat: "Domestic",
		avgGrownupWeight: "5-8 kg (males can be larger)",
		avgSize: "48-100 cm in length including tail",
		preferredFood: "Carnivorous: commercial cat food, meat",
		species: "Felis catus",
		color: "Variety of colors and patterns, including tabby, solid, bicolor, and more",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "4-6 kittens per litter",
		class: "Mammal"
	},
	ojos_azules_cat: {
		name: "Ojos Azules Cat",
		lifespan: "12-15 years",
		habitat: "Domestic",
		avgGrownupWeight: "3-5 kg",
		avgSize: "30-40 cm in length",
		preferredFood: "Carnivorous: commercial cat food, meat",
		species: "Felis catus",
		color: "Variety of colors, notable for striking blue eyes",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "4-6 kittens per litter",
		class: "Mammal"
	},
	scarlet_tanager: {
		name: "Scarlet Tanager",
		lifespan: "3-5 years in the wild",
		habitat: "Deciduous and mixed woodlands, forests",
		avgGrownupWeight: "23-38 g",
		avgSize: "16-19 cm in length, wingspan 25-30 cm",
		preferredFood: "Omnivorous: insects, fruits, berries",
		species: "Piranga olivacea",
		color: "Bright red with black wings and tail (males), yellowish-green with darker wings (females)",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "3-5 eggs per clutch",
		class: "Bird"
	},
	southern_festoon: {
		name: "Southern Festoon",
		lifespan: "2-3 weeks as adults",
		habitat: "Grasslands, meadows, and open woodlands in Southern Europe",
		avgGrownupWeight: "0.5-1 g",
		avgSize: "5-7 cm wingspan",
		preferredFood: "Herbivorous: larvae feed on Aristolochia plants, adults feed on nectar",
		species: "Zerynthia polyxena",
		color: "Yellow with black, red, and blue markings",
		reproduction: "Egg-laying",
		avgNumberOfOffsprings: "Several dozen eggs laid on host plants",
		class: "Insect"
	},
	khao_manee_cat: {
		name: "Khao Manee Cat",
		lifespan: "10-15 years",
		habitat: "Domestic",
		avgGrownupWeight: "3-5 kg",
		avgSize: "30-40 cm in length",
		preferredFood: "Carnivorous: commercial cat food, meat",
		species: "Felis catus",
		color: "Pure white with striking blue, green, or odd-colored eyes",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "4-6 kittens per litter",
		class: "Mammal"
	},
	toucan: {
		name: "Toucan",
		lifespan: "15-20 years",
		habitat: "Tropical and subtropical rainforests in Central and South America",
		avgGrownupWeight: "300-700 g depending on species",
		avgSize: "29-63 cm in length including bill",
		preferredFood: "Omnivorous: fruits, insects, small reptiles, and eggs",
		species: "Ramphastidae family",
		color: "Brightly colored plumage with a large, colorful bill",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "2-4 eggs per clutch",
		class: "Bird"
	},
	bald_eagle: {
		name: "Bald Eagle",
		lifespan: "20-30 years in the wild",
		habitat: "Near large bodies of open water such as lakes, rivers, and coastal regions in North America",
		avgGrownupWeight: "3-6.3 kg",
		avgSize: "70-102 cm in length, wingspan 180-230 cm",
		preferredFood: "Carnivorous: primarily fish, but also small mammals, birds, and carrion",
		species: "Haliaeetus leucocephalus",
		color: "Dark brown body with a white head and tail, yellow beak and feet",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "1-3 eggs per clutch",
		class: "Bird"
	},
	Axolotl: {
		name: "Axolotl",
		lifespan: "10-15 years in captivity",
		habitat: "Freshwater lakes and canals in Mexico, particularly Lake Xochimilco",
		avgGrownupWeight: "60-200 g",
		avgSize: "15-45 cm",
		preferredFood: "Carnivorous: worms, insects, small fish, and other small aquatic animals",
		species: "Ambystoma mexicanum",
		color: "Varies: wild types are usually dark with speckling, while captive-bred can be white, pink, or gold",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "100-300 eggs per clutch",
		class: "Amphibian"
	},
	macaw: {
		name: "Macaw",
		lifespan: "30-50 years, some species up to 75 years in captivity",
		habitat: "Tropical rainforests, savannas, and woodlands of Central and South America",
		avgGrownupWeight: "900-1200 g depending on species",
		avgSize: "76-100 cm in length including tail",
		preferredFood: "Omnivorous: seeds, nuts, fruits, leaves, and occasionally insects",
		species: "Ara genus",
		color: "Brightly colored plumage, often in shades of blue, red, green, and yellow",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "2-4 eggs per clutch",
		class: "Bird"
	},
	blue_tit: {
		lifespan: "2-3 years in the wild, up to 15 years in captivity",
		habitat: "Woodlands, gardens, hedgerows, and parks throughout Europe and western Asia",
		avgGrownupWeight: "9-12 g",
		avgSize: "12 cm in length, wingspan 17-20 cm",
		preferredFood: "Omnivorous: insects, seeds, nuts, and berries",
		species: "Cyanistes caeruleus",
		color: "Blue cap, wings, and tail with yellow underparts and greenish back",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "7-12 eggs per clutch",
		class: "Bird"
	},
	"Alpine Ibex": {
		lifespan: "10-14 years in the wild",
		habitat: "Mountainous regions in the European Alps",
		avgGrownupWeight: "65-100 kg (males), 45-55 kg (females)",
		avgSize: "1.3-1.5 m in length, 70-90 cm at shoulder height",
		preferredFood: "Herbivorous: grasses, herbs, and leaves",
		species: "Capra ibex",
		color: "Brownish-gray with lighter underparts and large, backward-curving horns",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "1-2 kids per birth",
		class: "Mammal"
	},
	"Grizzly Bear": {
		lifespan: "20-25 years in the wild, up to 30 years in captivity",
		habitat: "Forests, alpine meadows, and tundra in North America",
		avgGrownupWeight: "180-360 kg (males), 130-200 kg (females)",
		avgSize: "1.8-2.4 m in length, 1-1.2 m at shoulder height",
		preferredFood: "Omnivorous: berries, roots, salmon, small mammals, and carrion",
		species: "Ursus arctos horribilis",
		color: "Brown with grizzled (gray-tipped) fur",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "1-4 cubs per litter",
		class: "Mammal"
	},
	"Giant Swallowtail": {
		lifespan: "6-14 days as adults",
		habitat: "Woodlands, fields, gardens, and citrus groves in North and Central America",
		avgGrownupWeight: "0.5-1 g",
		avgSize: "10-16 cm wingspan",
		preferredFood: "Herbivorous: larvae feed on leaves of citrus plants, adults feed on nectar from flowers",
		species: "Papilio cresphontes",
		color: "Black wings with yellow bands and spots, underside is yellow with blue and red spots",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "Several hundred eggs laid singly on host plants",
		class: "Insect"
	},
	"Blue Morpho": {
		lifespan: "115 days (about 4 months) from egg to adult",
		habitat: "Tropical rainforests in Central and South America",
		avgGrownupWeight: "0.3-0.5 g",
		avgSize: "15-20 cm wingspan",
		preferredFood: "Herbivorous: larvae feed on leaves, adults feed on rotting fruit, fungi, and tree sap",
		species: "Morpho menelaus",
		color: "Brilliant blue upper wings, brown underside with eyespots for camouflage",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "Several hundred eggs laid singly on host plants",
		class: "Insect"
	},
	"Domestic Water Buffalo": {
		lifespan: "18-25 years",
		habitat: "Wetlands, swamps, and agricultural lands in tropical and subtropical regions",
		avgGrownupWeight: "400-900 kg (females), 700-1200 kg (males)",
		avgSize: "2.4-3 m in length, 1.5-1.8 m at shoulder height",
		preferredFood: "Herbivorous: grasses, aquatic plants, and crop residues",
		species: "Bubalus bubalis",
		color: "Generally dark gray to black",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "1 calf per birth",
		class: "Mammal"
	},
	"Tabby Cat": {
		lifespan: "12-15 years on average",
		habitat: "Domestic",
		avgGrownupWeight: "3.6-7.2 kg (males), 3.2-5.4 kg (females)",
		avgSize: "23-25 cm in height, 46-51 cm in length",
		preferredFood: "Carnivorous: commercial cat food, meat",
		species: "Felis catus",
		color: "Varies: distinct coat pattern with stripes, swirls, or spots",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "3-5 kittens per litter on average",
		class: "Mammal"
	},
	"Persian Cat": {
		lifespan: "10-15 years on average, some live up to 20 years",
		habitat: "Domestic",
		avgGrownupWeight: "3.6-6.8 kg (males), 3.2-5.4 kg (females)",
		avgSize: "25-30 cm in height, 30-50 cm in length",
		preferredFood: "Carnivorous: commercial cat food, meat",
		species: "Felis catus",
		color: "Varies: long-haired breed with various coat colors and patterns",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "3-4 kittens per litter on average",
		class: "Mammal"
	},
	"Siberian Husky": {
		lifespan: "12-15 years on average",
		habitat: "Domestic",
		avgGrownupWeight: "20-27 kg (males), 16-23 kg (females)",
		avgSize: "50-60 cm in height, 50-60 cm in length",
		preferredFood: "Omnivorous: commercial dog food, meat",
		species: "Canis lupus familiaris",
		color: "Varies: commonly black, white, gray, or a mix with distinctive facial markings",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "4-6 puppies per litter on average",
		class: "Mammal"
	},
	"Chinese Alligator": {
		lifespan: "50-70 years in the wild, up to 80 years in captivity",
		habitat: "Freshwater habitats such as rivers, streams, and marshes in eastern China",
		avgGrownupWeight: "20-45 kg",
		avgSize: "1.5-2.1 m in length",
		preferredFood: "Carnivorous: fish, amphibians, small mammals, and birds",
		species: "Alligator sinensis",
		color: "Dark olive-green with lighter underbelly and distinct bony plates on the head",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "10-50 eggs per nest, depending on environmental conditions",
		class: "Reptile"
	},
	"Pacific Orange-spine Unicornfish": {
		lifespan: "Unknown (varies among species)",
		habitat: "Coral reefs and rocky areas in the Pacific Ocean, particularly around Hawaii and French Polynesia",
		avgGrownupWeight: "Up to 1 kg",
		avgSize: "30-50 cm in length",
		preferredFood: "Herbivorous: primarily algae and small invertebrates",
		species: "Naso lituratus (also includes other species in the Naso genus)",
		color: "Bright blue body with orange spots, a distinctive horn-like projection from its forehead",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "Varies depending on species",
		class: "Fish"
	},
	"Ocellaris Clownfish": {
		lifespan: "6-10 years in the wild, up to 20 years in captivity",
		habitat: "Coral reefs and lagoons in the Indo-Pacific region",
		avgGrownupWeight: "Up to 100 g",
		avgSize: "7-12 cm in length",
		preferredFood: "Omnivorous: algae, zooplankton, and small crustaceans",
		species: "Amphiprion ocellaris",
		color: "Bright orange with white bands outlined in black",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "Hundreds of eggs per clutch, cared for by the male",
		class: "Fish"
	},
	"Sandbar Shark": {
		lifespan: "20-30 years",
		habitat: "Temperate and tropical waters worldwide, typically found near continental and insular shelves",
		avgGrownupWeight: "Up to 159 kg (males), up to 91 kg (females)",
		avgSize: "2-2.5 m in length",
		preferredFood: "Carnivorous: fish, rays, crustaceans, and cephalopods",
		species: "Carcharhinus plumbeus",
		color: "Gray to brownish-gray upper body with a white underside",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "1-14 pups per litter, with a 1-3 year reproductive cycle",
		class: "Fish"
	},
	"African Bush Elephant": {
		lifespan: "Up to 60-70 years in the wild",
		habitat: "Various habitats including savannas, forests, and deserts in sub-Saharan Africa",
		avgGrownupWeight: "Up to 6,000 kg (male), up to 3,000-4,000 kg (female)",
		avgSize: "2.5-4 m tall at the shoulder, 6-7 m in length",
		preferredFood: "Herbivorous: primarily grasses, leaves, fruits, and bark",
		species: "Loxodonta africana",
		color: "Gray to brownish-gray skin",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "1 calf every 2-4 years",
		class: "Mammal"
	},
	"Yellow Tang": {
		lifespan: "7-10 years in the wild, up to 20 years in captivity",
		habitat: "Reef environments and shallow lagoons in the Pacific Ocean, particularly around Hawaii",
		avgGrownupWeight: "Up to 100 g",
		avgSize: "12-15 cm in length",
		preferredFood: "Herbivorous: primarily algae and small invertebrates",
		species: "Zebrasoma flavescens",
		color: "Vibrant yellow body with a white spine along the base of the tail fin",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "Eggs hatch into larvae which eventually settle and develop into adults",
		class: "Fish"
	},
	"Siamese Fighting Fish": {
		lifespan: "2-5 years on average",
		habitat: "Freshwater habitats such as rice paddies, shallow ponds, and slow-moving streams in Southeast Asia",
		avgGrownupWeight: "Up to 15 g",
		avgSize: "6-8 cm in length",
		preferredFood: "Carnivorous: primarily insects, larvae, and small crustaceans",
		species: "Betta splendens",
		color: "Vibrant colors and elaborate fins, including shades of blue, red, green, and white",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "Up to several hundred eggs laid in bubble nests by the male",
		class: "Fish"
	},
	"Spinner Dolphin": {
		lifespan: "20-25 years on average",
		habitat: "Tropical and subtropical waters worldwide, often near continental shelves and islands",
		avgGrownupWeight: "Up to 80-100 kg",
		avgSize: "1.7-2.3 m in length",
		preferredFood: "Carnivorous: primarily fish, squid, and small crustaceans",
		species: "Stenella longirostris",
		color: "Gray with a distinct three-part color pattern: dark gray on top, light gray on the sides, and white underside",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "Usually 1 calf per birth",
		class: "Mammal"
	},
	"Callanthiidae": {
		lifespan: "Varies among species",
		habitat: "Deep-sea environments, typically found on continental slopes and seamounts",
		avgGrownupWeight: "Varies among species",
		avgSize: "Varies among species",
		preferredFood: "Carnivorous: feeds on small fish, crustaceans, and mollusks",
		species: "Various species within the Callanthiidae family",
		color: "Varies among species, often brightly colored with distinctive patterns",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "Varies among species",
		class: "Fish"
	},
	"Copperband Butterflyfish": {
		lifespan: "5-7 years in the wild",
		habitat: "Tropical coral reefs and lagoons in the Indo-Pacific region",
		avgGrownupWeight: "Up to 100 g",
		avgSize: "15-20 cm in length",
		preferredFood: "Omnivorous: feeds primarily on coral polyps, small invertebrates, and algae",
		species: "Chelmon rostratus",
		color: "White body with black vertical bands and a prominent coppery-orange band across its face",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "Eggs are released into the water and develop into larvae",
		class: "Fish"
	},
	"Nile Crocodile": {
		lifespan: "40-50 years in the wild, up to 80-100 years in captivity",
		habitat: "Freshwater habitats such as rivers, lakes, and marshes in sub-Saharan Africa",
		avgGrownupWeight: "Up to 225-550 kg",
		avgSize: "3.5-5 m in length, with some individuals reaching up to 6 m",
		preferredFood: "Carnivorous: fish, reptiles, birds, and mammals",
		species: "Crocodylus niloticus",
		color: "Dark bronze-green with black spots and bands on the body and tail",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "20-80 eggs per nest, with hatchlings cared for by the female",
		class: "Reptile"
	},
	"Intellagama lesueurii": {
		lifespan: "10-20 years in the wild, up to 30 years in captivity",
		habitat: "Eastern Australia, inhabiting forests, woodlands, and near water sources such as rivers and lakes",
		avgGrownupWeight: "300-600 grams",
		avgSize: "60-80 cm in length, including the tail",
		preferredFood: "Omnivorous: diet includes insects, small mammals, fish, and vegetation",
		species: "Intellagama lesueurii",
		color: "Varies; typically green to brown with dark bands and markings, juveniles often have brighter colors",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "6-18 eggs per clutch",
		class: "Reptile"
	},
	"Red Lionfish": {
		lifespan: "5-10 years in the wild",
		habitat: "Coral reefs and rocky crevices in the Indo-Pacific region, also found in the Atlantic Ocean",
		avgGrownupWeight: "Up to 1 kg",
		avgSize: "25-38 cm in length",
		preferredFood: "Carnivorous: feeds on small fish, crustaceans, and mollusks",
		species: "Pterois volitans (and Pterois miles for some similar species)",
		color: "Red to dark brown with white stripes and spines",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "Several thousands of eggs released into the water column",
		class: "Fish"
	},
	bee: {
		lifespan: "Varies among species; typically several weeks to a few months",
		habitat: "Varies widely; bees are found on every continent except Antarctica, predominantly in gardens, forests, and agricultural areas",
		avgGrownupWeight: "Approximately 0.1-1 gram",
		avgSize: "Approximately 0.8-2.5 cm in length",
		preferredFood: "Herbivorous: primarily feeds on nectar and pollen collected from flowers",
		species: "There are over 20,000 known species of bees, belonging to the superfamily Apoidea",
		color: "Varies among species; commonly yellow and black striped, but can range from metallic blue-green to solid black",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "Varies among species; a single queen bee can lay up to 2,000 eggs per day in peak season",
		class: "Insect"
	},
	hare: {
		lifespan: "1-9 years, depending on species and environmental factors",
		habitat: "Varies widely; found in grasslands, meadows, woodlands, and tundra regions across Europe, Asia, Africa, and North America",
		avgGrownupWeight: "2-5 kg",
		avgSize: "40-70 cm in length",
		preferredFood: "Herbivorous: primarily feeds on grasses, herbs, and twigs",
		species: "Several species within the genus Lepus",
		color: "Varies among species; typically shades of brown or gray, with some species exhibiting seasonal color changes",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "1-8 leverets per litter, depending on species and environmental conditions",
		class: "Mammal"
	},
	"Camargue Horse": {
		lifespan: "20-30 years",
		habitat: "Camargue region in the south of France, primarily found in wetlands, marshes, and salt flats",
		avgGrownupWeight: "400-500 kg",
		avgSize: "130-150 cm at the withers",
		preferredFood: "Herbivorous: primarily feeds on grasses, reeds, and other vegetation found in its habitat",
		species: "Equus ferus caballus",
		color: "Gray to white coat, known for its light coloration which helps with heat reflection in its hot and sunny habitat",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "1 foal per birth",
		class: "Mammal"
	},
	"Cotentin Donkey": {
		lifespan: "25-35 years",
		habitat: "Originally from the Cotentin Peninsula in Normandy, France; found in various habitats including pastures and meadows",
		avgGrownupWeight: "300-400 kg",
		avgSize: "110-130 cm at the withers",
		preferredFood: "Herbivorous: primarily feeds on grasses, hay, and other vegetation",
		species: "Equus africanus asinus",
		color: "Gray to brown coat, often with a lighter underbelly",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "1 foal per birth",
		class: "Mammal"
	},
	"Mule": {
		lifespan: "25-30 years",
		habitat: "Varies widely depending on human activity; found in agricultural settings, ranches, and sometimes wild environments",
		avgGrownupWeight: "350-500 kg",
		avgSize: "140-160 cm at the withers",
		preferredFood: "Herbivorous: primarily feeds on grasses, hay, and grains",
		species: "Equus asinus x Equus caballus hybrid",
		color: "Varies widely depending on the parent species; can be any color found in horses or donkeys",
		reproduction: "Sterile hybrid; mules are typically sterile and cannot reproduce",
		avgNumberOfOffsprings: "Mules do not reproduce; they are the offspring of a male donkey (jack) and a female horse (mare)",
		class: "Mammal"
	},
	"Northern Giraffe": {
		lifespan: "20-25 years in the wild, up to 30 years in captivity",
		habitat: "Savannas, woodlands, and dry forests in parts of sub-Saharan Africa, including countries like Kenya, Uganda, and South Sudan",
		avgGrownupWeight: "800-1,400 kg",
		avgSize: "5-6 m tall at the shoulder, with males taller than females",
		preferredFood: "Herbivorous: primarily feeds on leaves, shoots, and fruits from acacia and other trees",
		species: "Giraffa camelopardalis",
		color: "Yellowish to brown coat with irregular patches of darker spots; northern giraffes have lighter coats than their southern counterparts",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "Usually one calf per birth, after a gestation period of about 15 months",
		class: "Mammal"
	},
	"African Leopard": {
		lifespan: "12-17 years in the wild, up to 23 years in captivity",
		habitat: "Varies widely across sub-Saharan Africa, including forests, savannas, and mountainous regions",
		avgGrownupWeight: "30-70 kg",
		avgSize: "1.5-2.1 m in length, with a tail length of 0.6-1.1 m",
		preferredFood: "Carnivorous: hunts a variety of prey including antelopes, gazelles, and smaller mammals",
		species: "Panthera pardus",
		color: "Yellow to gold with black rosettes and spots; the coloration helps provide camouflage in different habitats",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "2-3 cubs per litter, born after a gestation period of approximately 90-105 days",
		class: "Mammal"
	},
	"Barbary Lion": {
		lifespan: "Estimated to be similar to other lion subspecies, around 10-14 years in the wild",
		habitat: "Historically found in North Africa, particularly in the Atlas Mountains and surrounding regions",
		avgGrownupWeight: "200-250 kg for males, slightly smaller for females",
		avgSize: "2.5-3.3 m in length, including tail",
		preferredFood: "Carnivorous: hunts large mammals such as gazelles, zebras, and buffalo",
		species: "Panthera leo leo",
		color: "Similar to other lion subspecies; tawny yellow to reddish-brown coat with a mane that varies in color from dark to blond",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "2-4 cubs per litter, born after a gestation period of approximately 100-110 days",
		class: "Mammal"
	},
	"Bengal Tiger": {
		lifespan: "10-15 years in the wild, up to 20-25 years in captivity",
		habitat: "Varies across India, Bangladesh, Nepal, Bhutan, and Myanmar; habitats include tropical and subtropical forests, mangroves, and grasslands",
		avgGrownupWeight: "180-258 kg for males, 100-160 kg for females",
		avgSize: "2.4-3 m in length, including tail",
		preferredFood: "Carnivorous: hunts large prey such as deer, wild boar, and occasionally smaller mammals and birds",
		species: "Panthera tigris tigris",
		color: "Orange to yellow coat with black stripes; the pattern of stripes is unique to each tiger, serving as camouflage in their habitat",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "2-4 cubs per litter, born after a gestation period of approximately 100-110 days",
		class: "Mammal"
	},
	"Jewel Bug": {
		lifespan: "Varies among species; typically several months to a year",
		habitat: "Found in tropical and subtropical regions worldwide, often on plants, bushes, and trees",
		avgGrownupWeight: "Varies among species; generally less than 1 gram",
		avgSize: "Approximately 1-2 cm in length",
		preferredFood: "Herbivorous: feeds on plant sap, often from seeds, flowers, and stems",
		species: "Family Scutelleridae, which includes numerous genera and species",
		color: "Highly variable and often vibrant, with metallic or iridescent hues of green, blue, red, and orange",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "Varies among species; eggs laid on plants and undergo several nymphal stages before reaching adulthood",
		class: "Insect"
	},
	"Hoplia": {
		lifespan: "Varies among species; typically several weeks to a few months",
		habitat: "Found in various habitats with flowering plants, including gardens, meadows, and grasslands",
		avgGrownupWeight: "Varies among species; generally less than 1 gram",
		avgSize: "Approximately 1-2 cm in length",
		preferredFood: "Herbivorous: feeds primarily on pollen, nectar, and petals of flowers",
		species: "Genus Hoplia, which includes numerous species of flower beetles",
		color: "Varies among species; often metallic green, blue, or brown with patterns of spots or stripes",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "Varies among species; eggs laid near flowers, larvae feed on plant material",
		class: "Insect"
	},
	"Asian Lady Beetle": {
		lifespan: "1-3 years",
		habitat: "Found in various habitats including gardens, agricultural fields, forests, and urban areas",
		avgGrownupWeight: "Less than 1 gram",
		avgSize: "5-8 mm in length",
		preferredFood: "Omnivorous: feeds on aphids, scale insects, and other soft-bodied insects, as well as pollen and nectar",
		species: "Harmonia axyridis",
		color: "Highly variable; typically orange to red with black spots, but can also be yellow to black or even melanistic (black with red spots)",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "Females can lay up to 1,500 eggs in their lifetime",
		class: "Insect"
	},
	"Scarlet Lily Beetle": {
		lifespan: "1-2 years",
		habitat: "Found in gardens, parks, and other areas where lilies and fritillaries are cultivated",
		avgGrownupWeight: "Less than 1 gram",
		avgSize: "Approximately 6-8 mm in length",
		preferredFood: "Herbivorous: feeds on the leaves, stems, and flowers of lilies and fritillaries",
		species: "Lilioceris lilii",
		color: "Bright scarlet red with black legs, head, antennae, and undersides",
		reproduction: "Oviparous",
		avgNumberOfOffsprings: "Females lay clusters of bright orange eggs on the undersides of lily leaves",
		class: "Insect"
	},
	"Southern Black Rhinoceros": {
		lifespan: "30-35 years in the wild, up to 45 years in captivity",
		habitat: "Found in savannas and semi-arid areas of southern Africa, including countries like Namibia, South Africa, Zimbabwe, and Kenya",
		avgGrownupWeight: "800-1,400 kg",
		avgSize: "1.4-1.8 m tall at the shoulder",
		preferredFood: "Herbivorous: primarily feeds on leaves, branches, and twigs of shrubs and trees",
		species: "Diceros bicornis bicornis",
		color: "Gray to brownish-gray in color, with two distinctive horns on the snout; horns are made of keratin and used for defense and dominance",
		reproduction: "Viviparous",
		avgNumberOfOffsprings: "Usually one calf per birth, after a gestation period of approximately 15-16 months",
		class: "Mammal"
	}



};
